FROM golang:1.22.5 AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o recipeApp .

FROM debian:bookworm-slim

WORKDIR /root/

COPY --from=build /app/recipeApp .

EXPOSE 8080

CMD ["./recipeApp"]
